import { VERSION, GENRES, AWARDS, RANKING_SOURCE_META, RANKING_SNAPSHOTS } from './catalog.js';

const esc = (value = '') => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yen = value => value ? `¥${Number(value).toLocaleString()}` : '価格情報なし';

export const NAV = [['popular','人気','◉'],['new','新着','✦'],['awards','受賞作','♛'],['genres','ジャンル','▦']];
export const SEARCH_MODES = [['title','タイトル'],['keyword','すべて'],['author','著者'],['publisher','出版社'],['isbn','ISBN']];
export const SORTS = [['standard','関連順'],['-releaseDate','新しい順'],['reviewCount','レビュー数'],['reviewAverage','評価順'],['+itemPrice','安い順'],['-itemPrice','高い順']];

export function chips(items, current, attr) {
  return `<div class="chips">${items.map(item => `<button class="${String(current)===String(item.id)?'active':''}" data-${attr}="${esc(item.id)}">${esc(item.label)}</button>`).join('')}</div>`;
}

export function intro(title, text) { return `<div class="section-intro"><h2>${esc(title)}</h2><p>${esc(text)}</p></div>`; }
function skeleton(){return `<div class="book-grid">${Array(8).fill('<div class="skeleton-card"><div></div><span></span><span></span></div>').join('')}</div>`}
function empty(title,text){return `<div class="empty"><div class="empty-icon">▢</div><h3>${esc(title)}</h3><p>${esc(text)}</p></div>`}

export function cards(state, books, ranked=false){
  if(state.loading)return skeleton();if(state.error)return empty('本を取得できません',state.error);if(!books.length)return empty('該当するKobo本がありません','条件を変えて探してみてください。');
  const favorite=id=>state.favorites.some(book=>book.id===id);
  return `<div class="book-grid">${books.map((book,index)=>`<article class="book-card"><button class="cover-button" data-open="${index}">${book.image?`<img src="${esc(book.image)}" alt="" loading="lazy">`:'<div class="cover-placeholder">BOOK</div>'}${ranked?`<b class="rank">${book.ranking?.rank||index+1}</b>`:''}</button><div class="book-meta"><button class="book-title" data-open="${index}">${esc(book.title)}</button>${book.awardMeta?`<p>${esc([book.awardMeta.edition,book.awardMeta.status].filter(Boolean).join(' · '))}</p>`:''}<p>${esc(book.author||'著者不明')}</p><div><strong>${yen(book.price)}</strong><button class="heart ${favorite(book.id)?'active':''}" data-fav="${index}">${favorite(book.id)?'♥':'♡'}</button></div></div></article>`).join('')}</div>`;
}

export function availableRankingSources(period){const external=Object.keys(RANKING_SNAPSHOTS[period]||{}).filter(id=>RANKING_SOURCE_META[id]).map(id=>({id,label:RANKING_SOURCE_META[id].label}));return[{id:'combined',label:'総合'},...external,{id:'kobo',label:'Koboレビュー'}]}
function rankingNote(state){if(state.source==='kobo')return'楽天Kobo APIのレビュー件数順をリアルタイム取得。外部ランキングのスクレイピングは行いません。';const bucket=RANKING_SNAPSHOTS[state.period]||{},ids=state.source==='combined'?Object.keys(bucket):[state.source];if(!ids.length)return'この期間の外部ランキングスナップショットはありません。';return ids.map(id=>{const snap=bucket[id],meta=RANKING_SOURCE_META[id];return`${meta?.attribution||id} / ${snap?.updatedAt||'日付不明'} / ${snap?.periodLabel||''}${snap?.genre?` / ${snap.genre}`:''}`}).join('　|　')+'。公開情報を基準日付きスナップショットとして管理し、アクセス時の自動スクレイピングは行いません。'}

export function popularView(state){const sources=availableRankingSources(state.period);return `<div class="segmented">${[['week','今週'],['month','今月'],['year','今年']].map(([id,label])=>`<button data-period="${id}" class="${state.period===id?'active':''}">${label}</button>`).join('')}</div>${chips(sources,state.source,'source')}${intro('いま読まれている本','公開ランキングとKoboレビューを照合し、電子書籍で読める本だけを表示。')}${cards(state,state.books,true)}<p class="source-note">${esc(rankingNote(state))}</p>`}
export function newView(state){return `${intro('新しく届いた本','楽天Koboのルートジャンルを発売日の新しい順に表示。予約作品も含まれます。')}${cards(state,state.books)}`}
export function awardView(state,awardYears){const award=AWARDS.find(item=>item.id===state.award)||AWARDS[0],years=awardYears.map(year=>({id:String(year),label:String(year)}));return `${chips(AWARDS,state.award,'award')}${chips(years,String(state.awardYear||''),'award-year')}${intro(award.label,`${award.candidatePolicy}。Kobo版が見つかった作品だけを表示します。`)}${cards(state,state.books)}<p class="source-note">賞データは公式・主催者情報を基準に静的管理。表示時はタイトル・著者でKobo APIへ照合します。</p>`}
export function genresView(state){if(!state.genre)return `${intro('ジャンルから探す','Kobo Genre Search APIで公式ジャンル階層へ動的にマッピング。小説ではライトノベルを除外し、成人向け作品は表示しません。')}<div class="genre-grid">${GENRES.map(g=>`<button data-genre="${g.id}"><span>${g.emoji}</span><strong>${esc(g.label)}</strong><b>›</b></button>`).join('')}</div>`;const genre=GENRES.find(g=>g.id===state.genre),resolved=state.genreResolved,text=resolved?`正式Koboジャンル: ${resolved.name}（${resolved.id}）${genre.excludeLightNovel?' / ライトノベル除外':''}`:`公式ジャンルIDを検索中。特定できない場合のみ「${genre.fallbackQuery}」で補助検索します。`;return `<button class="back-pill" data-back-genres>← ジャンル一覧</button>${intro(genre.label,text)}${cards(state,state.books)}`}

export function searchSheet(state,history){return `<div class="sheet full"><div class="sheet-head"><div class="search-field"><span>⌕</span><input id="search-input" value="${esc(state.query)}" placeholder="本のタイトル・著者を検索"></div><button class="icon-button" data-close-search>×</button></div>${chips(SEARCH_MODES.map(([id,label])=>({id,label})),state.searchMode,'search-mode')}<div class="sort-row"><span>並び替え</span><select id="sort-select">${SORTS.map(([id,label])=>`<option value="${id}" ${state.sort===id?'selected':''}>${label}</option>`).join('')}</select></div><div class="sheet-content">${state.query?cards(state,state.books):`<div class="history"><h3>最近の検索</h3>${history.length?history.map(item=>`<button data-history="${esc(item)}">${esc(item)}<b>›</b></button>`).join(''):'<p>検索履歴はこのiPhone内だけに保存されます。</p>'}</div>`}</div></div>`}

export function detailSheet(state,book){const fav=state.favorites.some(item=>item.id===book.id),award=book.awardMeta,awardText=award?[award.year,award.edition,award.status,award.rank?`${award.rank}位`:''].filter(Boolean).join(' · '):'';return `<div class="sheet-backdrop" data-close-detail><div class="sheet detail" data-stop><div class="drag"></div><button class="close-float" data-close-detail>×</button><div class="detail-top"><div class="detail-cover">${book.image?`<img src="${esc(book.image)}" alt="">`:'<div class="cover-placeholder">BOOK</div>'}</div><div><span class="detail-kicker">${esc(book.publisher||'Rakuten Kobo')}</span><h2>${esc(book.title)}</h2><p>${esc(book.author||'')}</p><strong class="detail-price">${yen(book.price)}</strong></div></div><div class="detail-actions"><button data-detail-fav>${fav?'♥ 保存済み':'♡ 気になる'}</button><a href="${esc(book.url)}" target="_blank" rel="noreferrer">Koboで見る ↗</a></div><div class="detail-info">${book.series?`<p><b>シリーズ</b><span>${esc(book.series)}</span></p>`:''}${book.salesDate?`<p><b>発売日</b><span>${esc(book.salesDate)}</span></p>`:''}${book.reviewCount?`<p><b>レビュー</b><span>★ ${Number(book.reviewAverage||0).toFixed(1)} / ${Number(book.reviewCount).toLocaleString()}件</span></p>`:''}${awardText?`<p><b>受賞情報</b><span>${esc(awardText)}</span></p>`:''}${award?.originalTitle?`<p><b>応募時題</b><span>${esc(award.originalTitle)}</span></p>`:''}<div class="caption">${esc(book.caption||'商品説明は楽天Koboで確認できます。')}</div></div></div></div>`}
export function favoritesView(state){return `<div class="sheet full"><div class="sheet-head"><div><div class="eyebrow">MY LIST</div><h2>気になる本</h2></div><button class="icon-button" data-close-favorites>×</button></div><div class="sheet-content">${state.favorites.length?cards(state,state.favorites):empty('まだ保存されていません','本の♡を押すと、このiPhoneに保存されます。')}</div></div>`}
export function layout(state,content,history){const title=NAV.find(item=>item[0]===state.tab)?.[1]||'Kobo Finder';return `<div class="app-shell"><header class="topbar"><div><div class="eyebrow">KOBO FINDER · v${VERSION}</div><h1>${title}</h1></div><div class="top-actions"><button class="icon-button" data-action="search">⌕</button><button class="icon-button fav-button" data-action="favorites">♡${state.favorites.length?`<span>${state.favorites.length}</span>`:''}</button></div></header><main class="content">${content}</main><nav class="bottom-nav">${NAV.map(([id,label,mark])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}"><b>${mark}</b><span>${label}</span></button>`).join('')}</nav></div>${state.searchOpen?searchSheet(state,history):''}${state.selected?detailSheet(state,state.selected):''}${state.favoritesOpen?favoritesView(state):''}`}
